# =============================================================================
# YouTube Music SQL - Export library to Excel
# =============================================================================
# Exports all songs and playlists to an Excel file for backup and comparison.
# Run with: python backend/export.py
# =============================================================================

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
import sys
import os
from datetime import datetime

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from app.database import get_db


def export_library():
    conn = get_db()
    cursor = conn.cursor()
    wb = openpyxl.Workbook()

    # --------------------------------------------------------------------------------
    # Sheet 1: All songs
    # --------------------------------------------------------------------------------
    ws_songs = wb.active
    ws_songs.title = "All Songs"

    header = [
        "ID",
        "Title",
        "Artist",
        "Album",
        "Duration (sec)",
        "Language",
        "YT Video ID",
        "Source",
        "Playlists",
    ]
    ws_songs.append(header)

    # Style header
    for cell in ws_songs[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1DB954")
        cell.alignment = Alignment(horizontal="center")

    cursor.execute("""
        SELECT
            s.id,
            s.title,
            s.artist,
            s.album,
            s.duration_sec,
            s.language,
            s.yt_video_id,
            s.source,
            STRING_AGG(p.name, ', ' ORDER BY p.name) AS playlists
        FROM songs s
        LEFT JOIN playlist_songs ps ON s.id = ps.song_id
        LEFT JOIN playlists p ON ps.playlist_id = p.id
        GROUP BY s.id, s.title, s.artist, s.album,
                 s.duration_sec, s.language, s.yt_video_id, s.source
        ORDER BY s.artist, s.title;
    """)

    for row in cursor.fetchall():
        ws_songs.append(
            [
                row["id"],
                row["title"],
                row["artist"],
                row["album"],
                row["duration_sec"],
                row["language"],
                row["yt_video_id"],
                row["source"],
                row["playlists"],
            ]
        )

    # Auto width
    for col in ws_songs.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        ws_songs.column_dimensions[col[0].column_letter].width = min(max_len + 4, 50)

    # --------------------------------------------------------------------------------
    # Sheet 2: Playlists summary
    # --------------------------------------------------------------------------------
    ws_playlists = wb.create_sheet("Playlists")

    header2 = ["Playlist", "Total Songs", "Autogenerated"]
    ws_playlists.append(header2)

    for cell in ws_playlists[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1DB954")
        cell.alignment = Alignment(horizontal="center")

    cursor.execute("""
        SELECT
            p.name,
            COUNT(ps.song_id) AS total_songs,
            p.is_autogenerated
        FROM playlists p
        LEFT JOIN playlist_songs ps ON p.id = ps.playlist_id
        GROUP BY p.id, p.name, p.is_autogenerated
        ORDER BY p.name;
    """)

    for row in cursor.fetchall():
        ws_playlists.append(
            [
                row["name"],
                row["total_songs"],
                "Yes" if row["is_autogenerated"] else "No",
            ]
        )

    for col in ws_playlists.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        ws_playlists.column_dimensions[col[0].column_letter].width = min(
            max_len + 4, 50
        )

    # ---------------------------------------------------------------------------------
    # Sheet 3: Songs not in any playlist except Música que te gustó
    # ---------------------------------------------------------------------------------
    ws_unorganized = wb.create_sheet("Unorganized")

    header3 = ["ID", "Title", "Artist", "Language"]
    ws_unorganized.append(header3)

    for cell in ws_unorganized[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="FF6B35")
        cell.alignment = Alignment(horizontal="center")

    cursor.execute("""
        SELECT s.id, s.title, s.artist, s.language
        FROM songs s
        JOIN playlist_songs ps ON s.id = ps.song_id
        WHERE ps.playlist_id = 1
        AND s.id NOT IN (
            SELECT song_id FROM playlist_songs WHERE playlist_id != 1
        )
        ORDER BY s.artist, s.title;
    """)

    for row in cursor.fetchall():
        ws_unorganized.append(
            [
                row["id"],
                row["title"],
                row["artist"],
                row["language"],
            ]
        )

    for col in ws_unorganized.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        ws_unorganized.column_dimensions[col[0].column_letter].width = min(
            max_len + 4, 50
        )

    # ---------------------------------------------------------------------------------
    # Save file
    # ---------------------------------------------------------------------------------
    cursor.close()
    conn.close()

    filename = f"ytmusic_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    wb.save(filename)
    print(f"Export complete: {filename}")
    print(f"  Total songs: {ws_songs.max_row - 1}")
    print(f"   Unorganized songs: {ws_unorganized.max_row - 1}")


if __name__ == "__main__":
    export_library()
