# =============================================================================
# YouTube Music SQL - Import from YouTube Music
# =============================================================================
# Connects to YouTube Music using ytmusicapi and imports playlists and songs
# into the local PostgreSQL database.
#
# Run with: python backend/ytmusic_import.py
# =============================================================================

from ytmusicapi import YTMusic
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from app.database import get_db

# Playlists to skip - autogenerated by YouTube Music
SKIP_PLAYLISTS = ["Episodes for Later"]

# Map YouTube Music names to local database names
PLAYLIST_NAME_MAP = {
    "Liked Music": "Música que te gustó",
    "Otros Idiomas": "Otros idiomas",
}

# Initialize ytmusicapi with browser credentials
ytmusic = YTMusic("auth/browser.json")


def get_or_create_playlist(cursor, name, yt_playlist_id, is_autogenerated=False):
    """Returns playlist id from DB, creating it if it doesn't exist."""
    cursor.execute("SELECT id FROM playlists WHERE name = %s", (name,))
    result = cursor.fetchone()
    if result:
        return result["id"]

    cursor.execute(
        """
        INSERT INTO playlists (name, is_autogenerated)
        VALUES (%s, %s)
        RETURNING id
    """,
        (name, is_autogenerated),
    )
    return cursor.fetchone()["id"]


def get_or_create_song(cursor, song):
    """Returns song id from DB, creating it if it doesn't exist."""
    video_id = song.get("videoId")
    title = song.get("title", "").strip()
    artists = song.get("artists") or []
    artist = artists[0]["name"] if artists else "Unknown"
    album_data = song.get("album")
    album = album_data["name"] if album_data else None
    duration_sec = song.get("duration_seconds")

    # Check by video ID first (most reliable)
    if video_id:
        cursor.execute("SELECT id FROM songs WHERE yt_video_id = %s", (video_id,))
        result = cursor.fetchone()
        if result:
            return result["id"], "existing"

    # Check by fuzzy title + artist
    cursor.execute(
        """
        SELECT id FROM songs
        WHERE similarity(
            unaccent(LOWER(title)),
            unaccent(LOWER(%s))
        ) > 0.85
        AND LOWER(artist) = LOWER(%s)
        LIMIT 1
    """,
        (title, artist),
    )
    result = cursor.fetchone()
    if result:
        return result["id"], "existing"

    # Insert new song
    cursor.execute(
        """
        INSERT INTO songs (
            title, artist, album, duration_sec,
            yt_video_id, language, source
        )
        VALUES (%s, %s, %s, %s, %s, %s, 'ytmusicapi')
        RETURNING id
    """,
        (title, artist, album, duration_sec, video_id, None),
    )
    return cursor.fetchone()["id"], "new"


def import_playlist(playlist):
    """Imports a single playlist and all its songs into the database."""
    name = PLAYLIST_NAME_MAP.get(playlist["title"], playlist["title"])
    playlist_id_yt = playlist["playlistId"]
    is_autogenerated = playlist["title"] == "Liked Music"

    print(f"\nImporting: {name}")

    # Fetch full playlist with songs
    details = ytmusic.get_playlist(playlist_id_yt, limit=1000)
    tracks = details.get("tracks", [])
    print(f"  Found {len(tracks)} tracks")

    conn = get_db()
    cursor = conn.cursor()

    try:
        # Get or create playlist in DB
        db_playlist_id = get_or_create_playlist(
            cursor, name, playlist_id_yt, is_autogenerated
        )

        new_count = 0
        existing_count = 0
        skipped_count = 0

        for position, track in enumerate(tracks, start=1):
            if not track.get("title"):
                skipped_count += 1
                continue

            song_id, status = get_or_create_song(cursor, track)

            if status == "new":
                new_count += 1

            else:
                existing_count += 1

            # Link song to playlist (ignore if already linked)
            cursor.execute(
                """
                INSERT INTO playlist_songs (playlist_id, song_id, position)
                VALUES (%s, %s, %s)
                ON CONFLICT (playlist_id, song_id) DO NOTHING
            """,
                (db_playlist_id, song_id, position),
            )

        conn.commit()
        print(f"  New songs: {new_count}")
        print(f"  Already existed: {existing_count}")
        print(f"  Skipped: {skipped_count}")

    except Exception as e:
        conn.rollback()
        print(f" Error: {e}")
    finally:
        cursor.close()
        conn.close()


def main():
    print("Starting YouTube Music import...")
    playlists = ytmusic.get_library_playlists(limit=25)

    for playlist in playlists:
        if playlist["title"] in SKIP_PLAYLISTS:
            print(f"\nSkipping: {playlist['title']}")
            continue
        import_playlist(playlist)

    print("\nImport complete.")


if __name__ == "__main__":
    main()
