import Link from "next/link";

async function getPlaylists() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000"}/playlists`,
    {
      cache: "no-store",
    },
  );
  return res.json();
}

export default async function PlaylistsSection() {
  const data = await getPlaylists();

  return (
    <div className="grid grid-cols-2 gap-4 md:grid-cols-3">
      {data.playlists.map((playlist) => (
        <Link
          key={playlist.id}
          href={`/playlists/${playlist.id}`}
          className="bg-gray-900 rounded-xl p-5 border border-gray-800 hover:border-red-500 transition-colors"
        >
          <p className="text-white font-medium mb-1">{playlist.name}</p>
          <p className="text-gray-400 text-sm">
            {playlist.total_songs} canciones
          </p>
          {playlist.is_autogenerated && (
            <span className="text-xs text-red-400 mt-2 block">
              Autogenerada
            </span>
          )}
        </Link>
      ))}
    </div>
  );
}
