# =============================================================================
# YouTube Music SQL - Main API
# =============================================================================
# FastAPI application with endpoints for songs and playlists.
# Run with: uvicorn backend.app.main:app --reload
# =============================================================================

from fastapi import FastAPI, HTTPException
from .database import get_db

app = FastAPI(
    title="YouTube Music SQL",
    description="API to manage and deduplicate a YouTube Music library",
    version="1.0.0",
)

# --------------------------------------------------------------------------------
# Health check
# --------------------------------------------------------------------------------


@app.get("/")
def root():
    return {"status": "ok", "message": "YouTube Music SQL API"}


# --------------------------------------------------------------------------------
# Songs
# --------------------------------------------------------------------------------


@app.get("/songs")
def get_songs():
    """Returns all songs in the catalog."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT id, title, artist, album, language, yt_video_id
            FROM songs
            ORDER BY artist, title;
        """)
        songs = cursor.fetchall()
        return {"total": len(songs), "songs": songs}
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Playlists
# --------------------------------------------------------------------------------


@app.get("/playlists")
def get_playlists():
    """Returns all playlists with their song count."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT
                p.id,
                p.name,
                p.is_autogenerated,
                COUNT(ps.song_id) AS total_songs
            FROM playlists p
            LEFT JOIN playlist_songs ps ON p.id = ps.playlist_id
            GROUP BY p.id, p.name, p.is_autogenerated
            ORDER BY p.id;
        """)
        playlists = cursor.fetchall()
        return {"total": len(playlists), "playlists": playlists}
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Duplicates
# --------------------------------------------------------------------------------


@app.get("/songs/duplicates")
def get_duplicates():
    """Returns fuzzy duplicate songs using trigram similarity."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT
                a.id            AS id_a,
                a.title         AS title_a,
                b.id            AS id_b,
                b.title         AS title_b,
                a.artist,
                ROUND(similarity(
                    unaccent(LOWER(a.title)),
                    unaccent(LOWER(b.title))
                )::NUMERIC, 2)  AS score
            FROM songs a
            JOIN songs b
                ON a.id < b.id
                AND LOWER(a.artist) = LOWER(b.artist)
                AND similarity(
                    unaccent(LOWER(a.title)),
                    unaccent(LOWER(b.title))
                ) > 0.85
            ORDER BY score DESC;
        """)
        duplicates = cursor.fetchall()
        return {"total": len(duplicates), "duplicates": duplicates}
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Smart search before adding a song
# --------------------------------------------------------------------------------


@app.get("/songs/search")
def search_songs(title: str, artist: str):
    """
    Searches for similar songs before adding a new one.
    Returns matches with a similarity score
    Use this before inserting to avoid duplicates.
    """
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT
                id,
                title,
                artist,
                album,
                yt_video_id,
                ROUND(similarity(
                    unaccent(LOWER(title)),
                    unaccent(LOWER(%s))
                )::NUMERIC, 2) AS score
            FROM songs
            WHERE
                similarity(
                    unaccent(LOWER(title)),
                    unaccent(LOWER(%s))
                ) > 0.5
                AND LOWER(artist) = LOWER(%s)
            ORDER BY score DESC;
        """,
            (title, title, artist),
        )
        results = cursor.fetchall()
        return {
            "query": {"title": title, "artist": artist},
            "total": len(results),
            "results": results,
        }
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Add a new song safely
# --------------------------------------------------------------------------------


@app.post("/songs")
def add_song(
    title: str,
    artist: str,
    album: str = None,
    duration_sec: int = None,
    release_year: int = None,
    genre: str = None,
    yt_video_id: str = None,
    language: str = None,
):
    """
    Adds a new song to the catalog.
    Automatically checks for duplicates before inserting.
    Rejects the insertion if a similar song already exists (score > 0.85).
    """
    conn = get_db()
    cursor = conn.cursor()
    try:
        # Step 1: check for duplicates
        cursor.execute(
            """
            SELECT
                id,
                title,
                artist,
                ROUND(similarity(
                    unaccent(LOWER(title)),
                    unaccent(LOWER(%s))
                )::NUMERIC, 2) AS score
            FROM songs
            WHERE
                similarity(
                    unaccent(LOWER(title)),
                    unaccent(LOWER(%s))
                ) > 0.85
                AND LOWER(artist) = LOWER(%s)
            ORDER BY score DESC
            LIMIT 1;
        """,
            (title, title, artist),
        )

        existing = cursor.fetchone()

        if existing:
            raise HTTPException(
                status_code=409,
                detail={
                    "message": "A similar song already exists",
                    "existing": {
                        "id": existing["id"],
                        "title": existing["title"],
                        "artist": existing["artist"],
                        "score": float(existing["score"]),
                    },
                },
            )

        # Step 2: insert the new song
        cursor.execute(
            """
            INSERT INTO songs (
                title, artist, album, duration_sec,
                release_year, genre, yt_video_id, language
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id, title, artist;
        """,
            (
                title,
                artist,
                album,
                duration_sec,
                release_year,
                genre,
                yt_video_id,
                language,
            ),
        )

        conn.commit()
        new_song = cursor.fetchone()
        return {"message": "Song added successfully", "song": new_song}

    finally:
        cursor.close()
        conn.close()
