# =============================================================================
# YouTube Music SQL - Main API
# =============================================================================
# FastAPI application with endpoints for songs and playlists.
# Run with: uvicorn backend.app.main:app --reload
# =============================================================================

from fastapi import FastAPI, HTTPException
from .database import get_db

app = FastAPI(
    title="YouTube Music SQL",
    description="API to manage and deduplicate a YouTube Music library",
    version="1.0.0",
)

# --------------------------------------------------------------------------------
# Health check
# --------------------------------------------------------------------------------


@app.get("/")
def root():
    return {"status": "ok", "message": "YouTube Music SQL API"}


# --------------------------------------------------------------------------------
# Songs
# --------------------------------------------------------------------------------


@app.get("/songs")
def get_songs():
    """Returns all songs in the catalog."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT id, title, artist, album, language, yt_video_id
            FROM songs
            ORDER BY artist, title;
        """)
        songs = cursor.fetchall()
        return {"total": len(songs), "songs": songs}
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Playlists
# --------------------------------------------------------------------------------


@app.get("/playlists")
def get_playlists():
    """Returns all playlists with their song count."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT
                p.id,
                p.name,
                p.is_autogenerated,
                COUNT(ps.song_id) AS total_songs
            FROM playlists p
            LEFT JOIN playlist_songs ps ON p.id = ps.playlist_id
            GROUP BY p.id, p.name, p.is_autogenerated
            ORDER BY p.id;
        """)
        playlists = cursor.fetchall()
        return {"total": len(playlists), "playlists": playlists}
    finally:
        cursor.close()
        conn.close()


# --------------------------------------------------------------------------------
# Duplicates
# --------------------------------------------------------------------------------


@app.get("/songs/duplicates")
def get_duplicates():
    """Returns fuzzy duplicate songs using trigram similarity."""
    conn = get_db()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT
                a.id            AS id_a,
                a.title         AS title_a,
                b.id            AS id_b,
                b.title         AS title_b,
                a.artist,
                ROUND(similarity(
                    unaccent(LOWER(a.title)),
                    unaccent(LOWER(b.title))
                )::NUMERIC, 2)  AS score
            FROM songs a
            JOIN songs b
                ON a.id < b.id
                AND LOWER(a.artist) = LOWER(b.artist)
                AND similarity(
                    unaccent(LOWER(a.title)),
                    unaccent(LOWER(b.title))
                ) > 0.6
            ORDER BY score DESC;
        """)
        duplicates = cursor.fetchall()
        return {"total": len(duplicates), "duplicates": duplicates}
    finally:
        cursor.close()
        conn.close()
