-- =============================================================================
-- YouTube Music SQL — Schema
-- =============================================================================
-- Run this file first, before any other SQL file.
-- PostgreSQL 14+
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Extensions
-- -----------------------------------------------------------------------------
-- Enables fuzzy text search (similarity, levenshtein)
-- Used to detect duplicate songs with slightly different titles
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Enables accent-insensitive search
-- Used alongside pg_trgm for better duplicate detection
CREATE EXTENSION IF NOT EXISTS unaccent;

-- --------------------------------------------------------------------------------
-- Table: songs
-- Core catalog. Every song lives here exactly once.
-- --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS songs (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    album TEXT,
    duration_sec INT,
    release_year INT,
    genre TEXT,
    yt_video_id TEXT UNIQUE,
    language TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------------------
-- Table: playlists
-- One row per playlist. A playlist can contain multiple songs.
-- --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS playlists (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    is_autogenerated BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------------------
-- Table: playlist_songs
-- Links songs to playlists (many-to-many relationship).
-- --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS playlist_songs (
    id SERIAL PRIMARY KEY,
    playlist_id INT NOT NULL REFERENCES playlists (id) ON DELETE CASCADE,
    song_id INT NOT NULL REFERENCES songs (id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- A song can only appear once per playlist
    CONSTRAINT uq_playlist_song UNIQUE (playlist_id, song_id)
);

-- --------------------------------------------------------------------------------
-- Table: song_backups
-- Stores a snapshot of a song before it is modified or deleted.
-- --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS song_backups (
    id SERIAL PRIMARY KEY,
    song_id INT REFERENCES songs (id) ON DELETE
    SET NULL,
        title TEXT,
        artist TEXT,
        album TEXT,
        duration_sec INT,
        release_year INT,
        genre TEXT,
        yt_video_id TEXT,
        language TEXT,
        reason TEXT NOT NULL CHECK (
            reason IN (
                'before_update',
                'before_delete',
                'duplicate_detected'
            )
        ),
        backed_up_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------------------
-- Indexes
-- Speed up the most common search patterns.
-- --------------------------------------------------------------------------------
-- Search songs by artist
CREATE INDEX IF NOT EXISTS idx_songs_artist ON songs (artist);

-- Fuzzy search on title and artist (used for duplicate detection)
CREATE INDEX IF NOT EXISTS idx_songs_title_trgm ON songs USING gin (title gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_songs_artist_trgm ON songs USING gin (artist gin_trgm_ops);

-- Look up songs within a playlist
CREATE INDEX IF NOT EXISTS idx_playlist_songs_playlist ON playlist_songs (playlist_id);