-- =============================================================================
-- YouTube Music SQL - Seed Data
-- =============================================================================
-- Test data to validate the schema and practice queries.
-- Real songs will be imported via ytmusicapi in Phase 2.
-- =============================================================================
-- --------------------------------------------------------------------------------
-- Playlists
-- --------------------------------------------------------------------------------
INSERT INTO playlists (name, description, is_autogenerated)
VALUES (
        'Música que te gustó',
        'Auto-generated by YouTube Music',
        TRUE
    ),
    ('English', 'Songs in English', FALSE),
    ('Español', 'Canciones en español', FALSE),
    ('Cristiana', 'Música cristiana', FALSE),
    ('???', 'Canciones random', FALSE),
    (
        'Otros idiomas',
        'Songs in other languages',
        FALSE
    );

-- -----------------------------------------------------------------------------
-- Songs
-- -----------------------------------------------------------------------------
-- Includes intentional duplicates to test detection queries:
--   - Same yt_video_id entered twice (exact duplicate)
--   - Same song with slight title variation (fuzzy duplicate)
INSERT INTO songs (
        title,
        artist,
        album,
        duration_sec,
        release_year,
        genre,
        yt_video_id,
        language
    )
VALUES -- English songs
    (
        'Blinding Lights',
        'The Weeknd',
        'After Hours',
        200,
        2020,
        'Pop',
        '4NRXx6U8ABQ',
        'en'
    ),
    (
        'Save Your Tears',
        'The Weeknd',
        'After Hours',
        215,
        2020,
        'Pop',
        'XXYlFuWEuKI',
        'en'
    ),
    (
        'Starboy',
        'The Weeknd',
        'Starboy',
        230,
        2016,
        'R&B',
        '34Na4j8AVgA',
        'en'
    ),
    (
        'Anti-Hero',
        'Taylor Swift',
        'Midnights',
        200,
        2022,
        'Pop',
        'b1kbLwvqugk',
        'en'
    ),
    (
        'Cruel Summer',
        'Taylor Swift',
        'Lover',
        178,
        2019,
        'Pop',
        'ic8j13piAhQ',
        'en'
    ),
    (
        'bad guy',
        'Billie Eilish',
        'WHEN WE ALL FALL ASLEEP',
        194,
        2019,
        'Pop',
        'DyDfgMOUjCI',
        'en'
    ),
    -- Spanish songs
    (
        'Hawái',
        'Maluma',
        'Papi Juancho',
        195,
        2020,
        'Reggaeton',
        'pK060iUFWXg',
        'es'
    ),
    (
        'TQG',
        'KAROL G',
        'MAÑANA SERÁ BONITO',
        183,
        2023,
        'Reggaeton',
        'jZGpkLElSu8',
        'es'
    ),
    (
        'PROVENZA',
        'KAROL G',
        'MAÑANA SERÁ BONITO',
        197,
        2022,
        'Reggaeton',
        NULL,
        'es'
    ),
    (
        'Flowers',
        'Miley Cyrus',
        'Endless Summer Vacation',
        200,
        2023,
        'Pop',
        'G7KNmW9a75Y',
        'es'
    ),
    -- Christian songs
    (
        'Waymaker',
        'Sinach',
        NULL,
        340,
        2015,
        'Gospel',
        'QM8jQHE5AAk',
        'en'
    ),
    (
        'Oceans',
        'Hillsong United',
        'Zion',
        522,
        2013,
        'Gospel',
        NULL,
        'en'
    ),
    -- Other languages
    (
        'Todo De Ti',
        'Rauw Alejandro',
        'Vice Versa',
        175,
        2021,
        'Reggaeton',
        'CFPLIaMpGrY',
        'es'
    ),
    -- Intentional exact duplicates (same yt_video_id)
    (
        'Blinding Lights',
        'The Weeknd',
        'After Hours',
        200,
        2020,
        'Pop',
        NULL,
        'en'
    ),
    -- Intentional fuzzy duplicates (same song, different title format)
    (
        'bad Guy',
        'Billie Eilish',
        'WHEN WE ALL FALL ASLEEP',
        194,
        2019,
        'Pop',
        NULL,
        'en'
    ),
    (
        'Hawaii',
        'Maluma',
        'Papi Juancho',
        195,
        2020,
        'Reggaeton',
        NULL,
        'es'
    );

-- --------------------------------------------------------------------------------
-- Playlist songs
-- --------------------------------------------------------------------------------
-- Música que te gustó (playlist_id = 1): all songs
-- English (playlist_id = 2): songs with language = 'en'
-- Español (playlist_id = 3): songs with language = 'es'
-- Cristiana (playlist_id = 4): gospel songs
-- ??? (playlist_id = 5): random songs
-- Otros idiomas (playlist_id = 6): songs with language not 'en' or 'es'
-- -----------------------------------------------------------------------------------
INSERT INTO playlist_songs (playlist_id, song_id)
VALUES -- Música que te gustó - todas
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10),
    (1, 11),
    (1, 12),
    (1, 13),
    -- English
    (2, 1),
    (2, 2),
    (2, 3),
    (2, 4),
    (2, 5),
    (2, 6),
    (2, 11),
    (2, 12),
    -- Español
    (3, 7),
    (3, 8),
    (3, 9),
    (3, 10),
    (3, 13),
    -- Cristiana
    (4, 11),
    (4, 12);

-- ??? y Otros idioma no tienen canciones en los datos de prueba
-- Real songs will be imported via ytmusicapi in Phase 2